### 2.1 Login
POST http://localhost:9091/api/auth/local
Content-Type: application/json

{
    "identifier": "",
    "password": ""
}

### 2.2 Register
POST http://localhost:9091/api/auth/local/register
Content-Type: application/json

{
    "username": "",
    "email": "",
    "password": ""
}

### 2.3 Forgot Password
POST http://localhost:9091/api/auth/forgot-password
Content-Type: application/json

{
    "email": ""
}

### 2.3.1 Reset Password (ใช้ token จาก email)
POST http://localhost:9091/api/auth/reset-password
Content-Type: application/json

{
    "password": "",
    "passwordConfirmation": "",
    "code": ""
}

### 2.4 Profile
GET http://localhost:9091/api/users/me
Authorization: Bearer <user-jwt-token>
